spring:
  datasource:
    username: 'app'
    password: '123456'
    url: 'jdbc:postgresql://postgres:5432/app'
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
management:
  endpoint:
    health:
      probes:
        enabled: true
integration:
  fns:
    base-url: 'https://suggestions.dadata.ru'
    token: ${DADATA_TOKEN}